### ISSUE TITLE
Improve error output

### ISSUE THREAD

**Issue by stefanbuck** [stefanbuck/hacktoberfest-hunt#2]
If the API returns an error e.g. the token is invalid or the rate limit kicks in, an error is shown in the console, but the output is quite verbose. Maybe it's enough to show the reasons body +http status code

**Comment by chaithanyaMarripati** [comment]
i can take this up, 
assign this to me @stefanbuck

**Comment by stefanbuck** [comment]
Go for it, thank you. Btw my last commit introduced a linting issue. I can fix it later or you can if you don't mind

**Comment by stefanbuck** [comment]
No pressure, but are you still interested @chaithanyaMarripati? Otherwise I'll mark this issue as available

**Comment by chaithanyaMarripati** [comment]
no im working on it @stefanbuck 
i will raise something ASAP
